# --- Part Two ---

# With your analysis of the manifold complete, you begin fixing the teleporter. However, as you open the side of the teleporter to replace the broken manifold, you are surprised to discover that it isn't a classical tachyon manifold - it's a quantum tachyon manifold.
#
# With a quantum tachyon manifold, only a single tachyon particle is sent through the manifold. A tachyon particle takes both the left and right path of each splitter encountered.
#
# Since this is impossible, the manual recommends the many-worlds interpretation of quantum tachyon splitting: each time a particle reaches a splitter, it's actually time itself which splits. In one timeline, the particle went left, and in the other timeline, the particle went right.
#
# To fix the manifold, what you really need to know is the number of timelines active after a single particle completes all of its possible journeys through the manifold.
#
# In the above example, there are many timelines. For instance, there's the timeline where the particle always went left:
#
# .......S.......
# .......|.......
# ......|^.......
# ......|........
# .....|^.^......
# .....|.........
# ....|^.^.^.....
# ....|..........
# ...|^.^...^....
# ...|...........
# ..|^.^...^.^...
# ..|............
# .|^...^.....^..
# .|.............
# |^.^.^.^.^...^.
# |..............
# Or, there's the timeline where the particle alternated going left and right at each splitter:
#
# .......S.......
# .......|.......
# ......|^.......
# ......|........
# ......^|^......
# .......|.......
# .....^|^.^.....
# ......|........
# ....^.^|..^....
# .......|.......
# ...^.^.|.^.^...
# .......|.......
# ..^...^|....^..
# .......|.......
# .^.^.^|^.^...^.
# ......|........
# Or, there's the timeline where the particle ends up at the same point as the alternating timeline, but takes a totally different path to get there:
#
# .......S.......
# .......|.......
# ......|^.......
# ......|........
# .....|^.^......
# .....|.........
# ....|^.^.^.....
# ....|..........
# ....^|^...^....
# .....|.........
# ...^.^|..^.^...
# ......|........
# ..^..|^.....^..
# .....|.........
# .^.^.^|^.^...^.
# ......|........
# In this example, in total, the particle ends up on 40 different timelines.
#
# Apply the many-worlds interpretation of quantum tachyon splitting to your manifold diagram. In total, how many different timelines would a single tachyon particle end up on?

def read_grid(filename):
    with open(filename, 'r') as f:
        return [list(line.rstrip('\n')) for line in f if line.strip()]

def find_start(grid):
    for r, row in enumerate(grid):
        for c, val in enumerate(row):
            if val == 'S':
                return r, c
    raise ValueError("No start position 'S' found.")

# def count_timelines(grid, r, c):
#     rows, cols = len(grid), len(grid[0])
#     # If out of bounds, this path ends
#     if not (0 <= r < rows and 0 <= c < cols):
#         return 0
#     # If at the last row, this is a valid timeline
#     if r == rows - 1:
#         return 1
#     cell = grid[r][c]
#     if cell == '^':
#         # Split: left and right, both go down
#         left = count_timelines(grid, r + 1, c - 1)
#         right = count_timelines(grid, r + 1, c + 1)
#         return left + right
#     else:
#         # Continue down
#         return count_timelines(grid, r + 1, c)  --> time consuming for larger input data as its a recursion

def count_timelines(grid, r, c, memo):
    rows, cols = len(grid), len(grid[0])
    if not (0 <= r < rows and 0 <= c < cols):
        return 0
    if r == rows - 1:
        return 1
    if (r, c) in memo:
        return memo[(r, c)]
    cell = grid[r][c]
    if cell == '^':
        left = count_timelines(grid, r + 1, c - 1, memo)
        right = count_timelines(grid, r + 1, c + 1, memo)
        memo[(r, c)] = left + right
    else:
        memo[(r, c)] = count_timelines(grid, r + 1, c, memo)
    return memo[(r, c)]

if __name__ == "__main__":
    grid = read_grid("tachyon_beams.txt")
    sr, sc = find_start(grid)
    memo = {}
    result = count_timelines(grid, sr + 1, sc, memo)
    print("Total number of timelines:", result)
    # Total number of timelines: 10357305916520